Update IBM Product Vulnerability information
cisagov/log4j-affected-db pull request #134
Opened 2021-12-16 03:32 UTC by kalbano1BM

#  #

## 🗣 Description ##

## 💭 Motivation and context ##

## 🧪 Testing ##

## 📷 Screenshots (if appropriate) ##

## ✅ Checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

2021-12-16 20:21 UTC, KwadwoBCISA approved these changes

2021-12-16 20:24 UTC, KwadwoBCISA approved these changes

2021-12-18 18:43 UTC, justmurphy requested changes
@kalbano1BM sorry for the delayed response.  I believe this was submitted as we were simultaneously updating the information on our end.  Could you please review the current IBM entries, and submit a new PR with any changes to be made for the IBM entries.  Thank you.

2021-12-22 19:53 UTC, justmurphy commented
Closing because update is to old REAME.md.  We have moved the data to a different markdown file (SOFTWARE-LIST.md).  Thank you for your submission, and feel free to add any updates in future PRs.

2021-12-22 19:53 UTC, closed without merging