Update SOFTWARE-LIST.md
cisagov/log4j-affected-db pull request #384
Opened 2021-12-23 18:53 UTC by rajendrapshrestha

Adding entries for Oracle Exadata and Oracle Enterprise Manager

#  #

## 🗣 Description ##

## 💭 Motivation and context ##

## 🧪 Testing ##

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

2021-12-27 16:23 UTC, iainDe requested changes
Please include affected version number of the products in quest and please include a link pointing to documentation  to Oracle's advisory/alert stating the status of these products.

2021-12-30 14:04 UTC, rajendrapshrestha commented
I have updated the info with requested info. Please review.

2021-12-30 14:11 UTC, justmurphy approved these changes
Thank you for the update.  We appreciate it.

2021-12-30 14:52 UTC, iainDe approved these changes

2021-12-30 14:52 UTC, merged