Update SOFTWARE-LIST.md with Snow Software information
cisagov/log4j-affected-db pull request #393
Opened 2021-12-26 20:07 UTC by AlastairPooley

Snow Software added

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

2021-12-27 18:17 UTC, iainDe submitted a review, later dismissed

2021-12-27 18:24 UTC, iainDe commented on SOFTWARE-LIST.md
> +| Snow Software | VM Access Proxy | v3.1 to v3.6 " Fixed | Yes | [Snow Software Commmunity Link](https://community.snowsoftware.com/s/feed/0D5690000B4U6hUCQS) | | | |
Line should read as the following: 
| Snow Software | VM Access Proxy | v3.1 to v3.6 I Fixed | Yes | [Snow Software Community Link](https://community.snowsoftware.com/s/feed/0D5690000B4U6hUCQS) | | | |

2021-12-27 18:26 UTC, iainDe requested changes
``

2021-12-28 09:58 UTC, AlastairPooley reviewed
Thanks iainDe

2021-12-29 13:29 UTC, justmurphy approved these changes
Thank you for the submission.

2021-12-29 14:00 UTC, iainDe approved these changes

2021-12-29 14:00 UTC, merged