Contributing adjustments
cisagov/log4j-affected-db pull request #425
Opened 2022-01-05 20:10 UTC by iainDe

#  #

## 🗣 Description ##

## 💭 Motivation and context ##

## 🧪 Testing ##

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

2022-01-05 20:13 UTC, iainDe commented
Let me know if this is satisfactory documentation to future contributors. From the CONTRIBUTING.md users would navigate the link to PULL-EXAMPLE.md

2022-01-05 23:10 UTC, chelsgr reviewed
I would suggest this section could be removed:

"Note: we are tracking multiple CVEs on the backend but are currently only displaying all the CVE-2021-44228. The multiple CVEs will not be listed in the table per the current request, instead the logic will determine and present a single status based on the available data in the template. "

That was included in the notes for context, but we probably don't need to keep it in the contributing doc - especially if we are expecting there may be some PRs for the other related CVEs moving forward.

The reporter field should also be removed from the template and example, since this field will be machine generated moving forward:
" reporter: cisagov"

2022-01-06 11:17 UTC, iainDe commented
> I would suggest this section could be removed:
> 
> "Note: we are tracking multiple CVEs on the backend but are currently only displaying all the [CVE-2021-44228](https://github.com/advisories/GHSA-jfh8-c2jp-5v3q). The multiple CVEs will not be listed in the table per the current request, instead the logic will determine and present a single status based on the available data in the template. "
> 
> That was included in the notes for context, but we probably don't need to keep it in the contributing doc - especially if we are expecting there may be some PRs for the other related CVEs moving forward.
> 
> The reporter field should also be removed from the template and example, since this field will be machine generated moving forward: " reporter: cisagov"

@chelsgr Changes made as suggested to the PULL-EXAMPLE.md. Eliminated the comment on tracking CVEs on the backend, and removed the two instances of the reporter being a tracked field.

2022-01-06 16:33 UTC, jsf9k reviewed
A few wording and formatting suggestions.

2022-01-06 16:33 UTC, jsf9k commented on PULL-EXAMPLE.md
> +For any additional questions feel free to submit an Issue request [here](https://github.com/cisagov/log4j-affected-db/issues)
```suggestion
For any additional questions feel free to [submit an Issue request](https://github.com/cisagov/log4j-affected-db/issues).
```

2022-01-06 16:33 UTC, jsf9k commented on PULL-EXAMPLE.md
> +  -
I suggest putting a dummy value here instead of an empty list item (i.e., the existing line containing just a single hyphen character).  If you want to leave this field blank then you should set it to an empty list, as is done, e.g., for `unaffected_versions`.
```suggestion
  - https://example.org/
```

2022-01-06 16:33 UTC, jsf9k commented on PULL-EXAMPLE.md
> +Thank you for contributing to CISA's Log4j-affected-db GitHub Repository! Please follow the steps listed below in order to add a product to the public repository. **Note:** To verify the accuracy of
```suggestion
Thank you for contributing to CISA's Log4j-affected-db GitHub Repository! Please follow the steps listed below in order to add a product to the public repository. **Note:** To assure the accuracy of data please only include products that have official advisories or alerts that verify the product's vulnerabilty status to  [CVE-2021-4104](https://nvd.nist.gov/vuln/detail/cve-2021-4104), [CVE-2021-44228](https://nvd.nist.gov/vuln/detail/CVE-2021-44228), [CVE-2021-45046](https://nvd.nist.gov/vuln/detail/CVE-2021-45046), and/or [CVE-2021-45105.](https://nvd.nist.gov/vuln/detail/CVE-2021-45105?s=09).
```

2022-01-06 16:33 UTC, jsf9k commented on PULL-EXAMPLE.md
> +**Step 1:** Go to the cisagov data .yml files for choosing the appropriate file to include your updates (example link). The files are separated based on the alphabetical first letter of the vendor na
```suggestion
**Step 1:** Go to the cisagov data .yml files and choose the appropriate file to include your updates (example link). The files are separated alphabetically based on the first letter of the vendor name. For example, 'CISA' would be located in [`cisagov_C.yml`](https://github.com/cisagov/data/cisagov_C.yml).
```

2022-01-06 16:33 UTC, jsf9k commented on PULL-EXAMPLE.md
> +   -	If you are adding it to the end of the file, ensure the entry ends before the file is closed out with: “...”
```suggestion
   - If you are adding it to the beginning of the file, ensure you are pasting it after `software:` and before the next entry starting with `- vendor:`.
   -	If you are adding it to the end of the file, ensure the entry ends before the file is closed out with `...`.
```

2022-01-06 16:33 UTC, jsf9k commented on PULL-EXAMPLE.md
> +**Step 4:** When you add content to the file, remove the '' or [] for fields which are replaced with values (strings '' or lists [] should be replaced as shown in the example below, with list values
```suggestion
**Step 4:** When you add content to the file, remove the `''` or `[]` for fields which are replaced with values (strings `''` or lists `[]` should be replaced as shown in the example below, with list values on the following line(s) starting with hyphen(s) `-`). The symbols should only remain used when fields remain empty. For example, `fixed_versions: []` in our example below remains as is, given there are no patched versions available for this entry.
```

2022-01-10 18:25 UTC, dav3r commented on PULL-EXAMPLE.md
> +located in [`cisagov_C.yml`](https://github.com/cisagov/data/cisagov_C.yml).
Here are some suggestions for this block:
* Add a link to the data directory (won't work right now, but will be correct after this PR is merged)
* Remove the "example link" text
* Correct the `cisagov_C.yml` URL (won't work right now, but will be correct after this PR is merged)
```suggestion
**Step 1:** Go to the [cisagov data .yml files](https://github.com/cisagov/log4j-affected-db/tree/develop/data/)
and choose the appropriate file to include your updates. 
The files are separated alphabetically based on the first letter of the
vendor name. For example, 'CISA' would be located in 
[`cisagov_C.yml`](https://github.com/cisagov/log4j-affected-db/blob/develop/data/cisagov_C.yml).
```

2022-01-10 19:06 UTC, dav3r commented on PULL-EXAMPLE.md
> +located in [`cisagov_C.yml`](https://github.com/cisagov/data/cisagov_C.yml).
@Lcerkov - sorry about that trailing whitespace in my suggestion above.  Thanks for fixing it in https://github.com/cisagov/log4j-affected-db/pull/425/commits/38fe6123ee712b7f35d3d31e014c7b0e6431767b. 👍

2022-01-10 22:15 UTC, jsf9k approved these changes

2022-01-10 22:28 UTC, mcdonnnj requested changes
I had some changes to suggest. I would also like to see the return of a `Contributing` section to `README.md` (such as restoring the one found in [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic/blob/develop/README.md#contributing)).

2022-01-10 22:28 UTC, mcdonnnj commented on PULL-EXAMPLE.md
> +        - <=8.6.4
```suggestion
          - <=8.4.6
          - <=8.5.3
          - <=8.6.4
```

2022-01-10 22:28 UTC, mcdonnnj commented on CONTRIBUTING.md
> +request](https://github.com/cisagov/log4j-affected-db/PULL-EXAMPLE.md), you will
Please add a subsection to this section directing people to go to the `PULL-EXAMPLE.md` file for directions.

Something loosely like:

```markdown
### Creating a pull request ###

Instructions for creating a pull request using the GitHub Web UI can be found
in [`PULL-EXAMPLE.md`](PULL-EXAMPLE.md).
```

```suggestion
request](https://github.com/cisagov/log4j-affected-db/pulls), you will
```

2022-01-11 15:39 UTC, Lcerkov approved these changes

2022-01-11 15:43 UTC, dav3r approved these changes
👍 👍

2022-01-11 17:57 UTC, mcdonnnj requested changes
One last formatting change after I ran both examples against our linters and a terminology change.

2022-01-11 17:57 UTC, mcdonnnj commented on PULL-EXAMPLE.md
> +    unauthenticated user input to the log4j component.
```suggestion
      unauthenticated user input to the log4j component.
```

2022-01-11 17:57 UTC, mcdonnnj commented on PULL-EXAMPLE.md
> +For any additional questions feel free to [submit an Issue request](https://github.com/cisagov/log4j-affected-db/issues).
```suggestion
For any additional questions feel free to [submit an Issue](https://github.com/cisagov/log4j-affected-db/issues).
```

2022-01-12 20:45 UTC, mcdonnnj approved these changes

2022-01-12 20:47 UTC, merged

2022-01-13 16:37 UTC, JeffBor commented on PULL-EXAMPLE.md
> +    cves:
Recommend adding **CVE-2021-44832** to template per #404