Update cisagov_N.yml
cisagov/log4j-affected-db pull request #435
Opened 2022-01-12 23:43 UTC by kyle-ni

#  #

## 🗣 Description ##

- Updated status of NI Products
- fixed typo in 'notes'
- removed duplicate entry

## 💭 Motivation and context ##

## 🧪 Testing ##

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - _eschew scope creep!_
- [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

2022-01-14 00:22 UTC, Lcerkov commented on data/cisagov_N.yml
>          affected_versions: []
```suggestion
        affected_versions:
          -Limited to deployments running Vertica, Cloudera, or Logstash
```

2022-01-14 00:23 UTC, Lcerkov commented on data/cisagov_N.yml
>          affected_versions: []
```suggestion
        affected_versions:
          -Limited to deployments running Vertica, Cloudera, or Logstash
```

2022-01-14 00:23 UTC, Lcerkov commented on data/cisagov_N.yml
>          affected_versions: []
```suggestion
        affected_versions:
          -Limited to deployments running Vertica, Cloudera, or Logstash
```

2022-01-14 00:24 UTC, Lcerkov commented on data/cisagov_N.yml
>          affected_versions: []
```suggestion
        affected_versions:
          -Limited to deployments running Vertica, Cloudera, or Logstash
```

2022-01-14 00:26 UTC, Lcerkov requested changes
@kyle-ni The logic behind the calculated "Status" field requires that there be content in the affected version field for the Status to = Affected. I suggested adding the language in the notes section to the affected versions section.

2022-01-14 17:17 UTC, kyle-ni commented
> 

@Lcerkov - Makes sense.  I missed how 'Status' was computed and the fact that it is an 'OR' of the individual CVEs.  Was attempting to communicate that we have investigated against all of the CVEs, but only vulnerable to one.

2022-01-14 20:12 UTC, Lcerkov commented
@kyle-ni  Ahh, is it only vulnerable to CVE-2021-44228? If so, I will make that change and then merge the PR.

2022-01-14 22:12 UTC, kyle-ni commented
> 

@Lcerkov Yes, that is correct.  Technically only CVE-2021-44228 applies for our products.

2022-01-18 14:37 UTC, Lcerkov approved these changes

2022-01-18 14:39 UTC, merged

2022-01-18 14:39 UTC, Lcerkov commented
@kyle-ni Thanks for the clarification- I fixed that and merged the update!